using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RegisterApi.Migrations
{
    /// <inheritdoc />
    public partial class AddSoldByPucIdToPaymentOrder : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"PaymentOrders\" ADD COLUMN IF NOT EXISTS \"SoldByPucId\" text;");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"PickupCenterInventoryItems\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"PickupCenterId\" integer NOT NULL, \"ProductId\" integer NOT NULL, \"Quantity\" integer NOT NULL, \"UpdatedAt\" timestamp with time zone NOT NULL, CONSTRAINT \"PK_PickupCenterInventoryItems\" PRIMARY KEY (\"Id\"));");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"PickupCenterOrders\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"PickupCenterId\" integer NOT NULL, \"PucId\" text NOT NULL, \"CenterName\" text NOT NULL, \"ContactName\" text NOT NULL, \"ContactPhone\" text NOT NULL, \"UtrNumber\" text NOT NULL, \"ScreenshotUrl\" text, \"ItemsJson\" text NOT NULL, \"SubTotalDp\" numeric(18,2) NOT NULL, \"DiscountPercent\" numeric(5,2) NOT NULL, \"DiscountAmount\" numeric(18,2) NOT NULL, \"TotalAmount\" numeric(18,2) NOT NULL, \"TotalBv\" numeric(18,2) NOT NULL, \"Status\" character varying(20) NOT NULL, \"RequestedAt\" timestamp with time zone NOT NULL, \"ProcessedAt\" timestamp with time zone, \"ProcessedByAdminId\" text, \"RejectionReason\" text, CONSTRAINT \"PK_PickupCenterOrders\" PRIMARY KEY (\"Id\"));");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_PickupCenterInventoryItems_PickupCenterId_ProductId\" ON \"PickupCenterInventoryItems\" (\"PickupCenterId\", \"ProductId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_PickupCenterOrders_PickupCenterId\" ON \"PickupCenterOrders\" (\"PickupCenterId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_PickupCenterOrders_Status\" ON \"PickupCenterOrders\" (\"Status\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PickupCenterInventoryItems");

            migrationBuilder.DropTable(
                name: "PickupCenterOrders");

            migrationBuilder.DropColumn(
                name: "SoldByPucId",
                table: "PaymentOrders");
        }
    }
}
