using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RegisterApi.Data;

#nullable disable

namespace RegisterApi.Migrations
{
    // Hand-written (same style as your other recent migrations) so it's idempotent.
    [Migration("20261004120000_AddPickupCenterReturnsAndWallet")]
    [DbContext(typeof(AppDbContext))]
    public partial class AddPickupCenterReturnsAndWallet : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""PickupCenterReturnRequests"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PickupCenterId"" integer NOT NULL,
    ""PucId"" text NOT NULL,
    ""CenterName"" text NOT NULL,
    ""ItemsJson"" text NOT NULL,
    ""SubTotalDp"" numeric(18,2) NOT NULL,
    ""DeductionPercent"" numeric(5,2) NOT NULL,
    ""DeductionAmount"" numeric(18,2) NOT NULL,
    ""CreditAmount"" numeric(18,2) NOT NULL,
    ""Reason"" text NULL,
    ""Status"" character varying(20) NOT NULL,
    ""RequestedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ""ProcessedAt"" timestamp with time zone NULL,
    ""ProcessedByAdminId"" text NULL,
    ""RejectionReason"" text NULL
);
CREATE INDEX IF NOT EXISTS ""IX_PickupCenterReturnRequests_PickupCenterId"" ON ""PickupCenterReturnRequests"" (""PickupCenterId"");
CREATE INDEX IF NOT EXISTS ""IX_PickupCenterReturnRequests_Status"" ON ""PickupCenterReturnRequests"" (""Status"");

CREATE TABLE IF NOT EXISTS ""PickupCenterWallets"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PickupCenterId"" integer NOT NULL,
    ""PucId"" text NOT NULL,
    ""Balance"" numeric(18,2) NOT NULL DEFAULT 0,
    ""TotalEarned"" numeric(18,2) NOT NULL DEFAULT 0,
    ""TotalWithdrawn"" numeric(18,2) NOT NULL DEFAULT 0,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PickupCenterWallets_PickupCenterId"" ON ""PickupCenterWallets"" (""PickupCenterId"");

CREATE TABLE IF NOT EXISTS ""PickupCenterWalletTransactions"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PickupCenterId"" integer NOT NULL,
    ""PucId"" text NOT NULL,
    ""Type"" character varying(20) NOT NULL,
    ""Amount"" numeric(18,2) NOT NULL,
    ""BalanceAfter"" numeric(18,2) NOT NULL,
    ""Source"" character varying(100) NOT NULL,
    ""Description"" text NULL,
    ""ReferenceId"" character varying(50) NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ""IX_PickupCenterWalletTransactions_PickupCenterId"" ON ""PickupCenterWalletTransactions"" (""PickupCenterId"");
CREATE INDEX IF NOT EXISTS ""IX_PickupCenterWalletTransactions_CreatedAt"" ON ""PickupCenterWalletTransactions"" (""CreatedAt"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS ""PickupCenterWalletTransactions"";
DROP TABLE IF EXISTS ""PickupCenterWallets"";
DROP TABLE IF EXISTS ""PickupCenterReturnRequests"";
");
        }
    }
}
