using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using RegisterApi.Data;
using RegisterApi.Models;
using RegisterApi.DTOs;

namespace RegisterApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class TreeController : ControllerBase
    {
        private readonly AppDbContext _db;
        private const int MaxLevel = 12;

        public TreeController(AppDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> GetDownlineTree()
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                          ?? User.FindFirst("UserId")?.Value;

                if (string.IsNullOrWhiteSpace(userId))
                    return Unauthorized(new { message = "Invalid or expired session token." });

                var user = await _db.Users
                    .FirstOrDefaultAsync(u => u.UserId == userId.Trim());

                if (user == null)
                    return NotFound(new { message = "Distributor profile missing in system ledger." });

                var treeResponse = await BuildTreeRecursiveAsync(user, currentLevel: 0);

                return Ok(treeResponse);
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = "Matrix canvas node generation failure", details = ex.Message });
            }
        }

        /// <summary>
        /// Recursively builds the full tree up to MaxLevel (12).
        /// Each node fetches its OWN direct children using SponsorId = node.UserId.
        /// </summary>
        private async Task<TreeResponseDto> BuildTreeRecursiveAsync(User node, int currentLevel)
        {
            var dto = await BuildNodeDtoAsync(node, currentLevel);

            // Stop recursing beyond level 12
            if (currentLevel >= MaxLevel)
            {
                dto.HasChildren = false;
                dto.Children = new List<TreeResponseDto>();
                return dto;
            }

            // Fetch children of THIS specific node (not the logged-in user)
            var directChildren = await _db.Users
                .Where(u => u.SponsorId == node.UserId)
                .OrderBy(u => u.UserId)
                .Take(10)
                .ToListAsync();

            foreach (var child in directChildren)
            {
                var childDto = await BuildTreeRecursiveAsync(child, currentLevel + 1);
                dto.Children.Add(childDto);
            }

            dto.HasChildren = dto.Children.Count > 0;

            // ✅ Total incentive for THIS node = commission on its own BV
            // PLUS the commission generated by every node in its entire downline
            // (each descendant's TotalIncentive already includes ITS own + further downline,
            // but what THIS node actually earns from each descendant is only that descendant's
            // EstimatedEarnings — i.e. descendant's BV * descendant's level-vs-this-node %).
            // Since levels here are already relative to the root of this recursion call,
            // summing each direct/indirect descendant's own EstimatedEarnings gives the correct total.
            dto.TotalIncentive = dto.EstimatedEarnings + SumDescendantEarnings(dto.Children);

            return dto;
        }

        /// <summary>
        /// Recursively sums EstimatedEarnings across all descendants (children, grandchildren, ... up to level 12).
        /// </summary>
        private double SumDescendantEarnings(List<TreeResponseDto> children)
        {
            double sum = 0;
            foreach (var child in children)
            {
                sum += child.EstimatedEarnings;
                sum += SumDescendantEarnings(child.Children);
            }
            return sum;
        }

        /// <summary>
        /// Builds a single node DTO.
        /// NOTE: IsEligibleForWithdrawal and CalculatedBv are auto-computed by the DTO
        /// from DirectCount — do NOT assign them manually.
        /// </summary>
        private async Task<TreeResponseDto> BuildNodeDtoAsync(User node, int level)
        {
            var directCount = await _db.Users.CountAsync(u => u.SponsorId == node.UserId);

            // ✅ Real BV: sum of this specific user's own PAID purchases.
            // Previously this was DirectCount * 600 (a placeholder), which showed
            // BV/incentive even for users who never bought anything — just because
            // they had downlines. Now it reflects actual purchase data.
            var realBv = await _db.Plans
                .Where(p => p.UserId == node.UserId && p.Status == PlanStatus.Paid)
                .SumAsync(p => (decimal?)p.TotalBv) ?? 0;

            var dto = new TreeResponseDto
            {
                Id = node.UserId,
                Name = node.Name,
                SponsorId = node.SponsorId ?? string.Empty,
                SponsorName = node.SponsorIdName ?? string.Empty,
                IdStatus = node.IdStatus ?? "inactive",
                Level = level,
                DirectCount = directCount,
                CalculatedBv = (int)realBv,
                HasChildren = directCount > 0,
            };

            dto.LevelCommissionPercentage = level switch
            {
                0 => 10.0,
                1 => 10.0,
                2 => 7.0,
                3 => 5.0,
                4 => 4.0,
                5 => 4.0,
                6 => 3.0,
                7 => 3.0,
                8 => 2.0,
                9 => 2.0,
                10 => 2.0,
                11 => 1.0,
                12 => 1.0,
                _ => 0.0
            };

            // Now correctly based on real BV, not team size.
            dto.EstimatedEarnings = dto.CalculatedBv * (dto.LevelCommissionPercentage / 100.0);

            return dto;
        }
    }
}